import { assetPath } from '@/lib/site-path';

export const portfolioPhotos = [
  {
    id: 'wedding-01',
    title: 'By the water',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-01-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-01-640.jpg',
    width: 1440,
    height: 1008,
    alt: 'A newly married couple sitting together beside a pond.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-02',
    title: 'Among the trees',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-02-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-02-640.jpg',
    width: 1440,
    height: 1011,
    alt: 'A wedding couple standing among tall forest trees.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-03',
    title: 'Just the two of us',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-03-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-03-640.jpg',
    width: 1152,
    height: 1440,
    alt: 'A couple touching foreheads beside a blue wedding car.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-04',
    title: 'Your favourite people',
    category: 'Wedding parties',
    image: '/images/portfolio/shelz-wedding-04-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-04-640.jpg',
    width: 1440,
    height: 960,
    alt: 'A wedding party celebrating together on a lakeside jetty.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-05',
    title: 'Signed with a smile',
    category: 'Wedding moments',
    image: '/images/portfolio/shelz-wedding-05-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-05-640.jpg',
    width: 1440,
    height: 1032,
    alt: 'A bride and groom smiling as they sign their wedding documents.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-06',
    title: 'The little things',
    category: 'Wedding moments',
    image: '/images/portfolio/shelz-wedding-06-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-06-640.jpg',
    width: 1152,
    height: 1440,
    alt: 'Close-up of wedding rings, joined hands and a floral bouquet.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-07',
    title: 'A moment above it all',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-07-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-07-640.jpg',
    width: 1440,
    height: 959,
    alt: 'A couple laughing together on a green hillside.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-08',
    title: 'Before the ceremony',
    category: 'Wedding parties',
    image: '/images/portfolio/shelz-wedding-08-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-08-640.jpg',
    width: 1440,
    height: 1440,
    alt: 'A wedding collage featuring a bride and two bridesmaids with bouquets.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-09',
    title: 'A toast to the day',
    category: 'Wedding parties',
    image: '/images/portfolio/shelz-wedding-09-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-09-640.jpg',
    width: 1440,
    height: 1017,
    alt: 'A bridal party laughing and raising glasses while getting ready.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-10',
    title: 'Side by side',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-10-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-10-640.jpg',
    width: 1440,
    height: 890,
    alt: 'A newly married couple walking hand in hand down an outdoor aisle.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-11',
    title: 'With a view',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-11-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-11-640.jpg',
    width: 1440,
    height: 959,
    alt: 'A wedding couple beside a wooden swing overlooking rolling hills.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-12',
    title: 'A day in frames',
    category: 'Wedding moments',
    image: '/images/portfolio/shelz-wedding-12-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-12-640.jpg',
    width: 1152,
    height: 1440,
    alt: 'Wedding photo collage with a bride, groom and classic cars.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-13',
    title: 'Sealed with a kiss',
    category: 'Couple portraits',
    image: '/images/portfolio/shelz-wedding-13-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-13-640.jpg',
    width: 1080,
    height: 1440,
    alt: 'A couple kissing beneath a draped garden wedding arch.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-14',
    title: 'The groom\u2019s crew',
    category: 'Wedding parties',
    image: '/images/portfolio/shelz-wedding-14-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-14-640.jpg',
    width: 1440,
    height: 958,
    alt: 'Groomsmen standing beside a blue classic car at the forest edge.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-15',
    title: 'Together for the occasion',
    category: 'Wedding parties',
    image: '/images/portfolio/shelz-wedding-15-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-15-640.jpg',
    width: 1440,
    height: 960,
    alt: 'A wedding party gathered in front of a timber barn.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-16',
    title: 'The joy before the vows',
    category: 'Wedding parties',
    image: '/images/portfolio/shelz-wedding-16-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-16-640.jpg',
    width: 1440,
    height: 960,
    alt: 'A bridal party in robes posing together on a garden lawn.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
  {
    id: 'wedding-17',
    title: 'Ready to celebrate',
    category: 'Wedding moments',
    image: '/images/portfolio/shelz-wedding-17-1440.jpg',
    thumbnail: '/images/portfolio/shelz-wedding-17-640.jpg',
    width: 1440,
    height: 847,
    alt: 'A wedding couple posing beside a floral reception welcome sign.',
    description: 'Wedding photography by Shelz Media.',
    demo: false,
  },
].map((photo) => ({
  ...photo,
  image: assetPath(photo.image),
  thumbnail: assetPath(photo.thumbnail),
}));
